<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGBREgFQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGBREgFQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGBREgFQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGBREgFQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGBREgFQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'GBREgFQ',
    'container.build_id' => '9612623a',
    'container.build_time' => 1696337113,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGBREgFQ');
