<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXUJN68t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXUJN68t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXUJN68t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXUJN68t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXUJN68t\App_KernelDevDebugContainer([
    'container.build_hash' => 'XUJN68t',
    'container.build_id' => 'b2608f51',
    'container.build_time' => 1696337494,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXUJN68t');
