<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKHTmx24\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKHTmx24/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKHTmx24.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKHTmx24\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKHTmx24\App_KernelDevDebugContainer([
    'container.build_hash' => 'KHTmx24',
    'container.build_id' => '5b5ccf6e',
    'container.build_time' => 1696342419,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKHTmx24');
